# Generated by Django 4.1.7 on 2023-03-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Prodect',
        ),
    ]
