# Generated by Django 4.1.7 on 2023-03-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0002_rename_product_prodect'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodect',
            name='image',
            field=models.ImageField(default='', upload_to='Images/'),
            preserve_default=False,
        ),
    ]
