# Generated by Django 4.1.7 on 2023-03-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0003_prodect_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
