# Generated by Django 4.1.7 on 2023-03-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0004_alter_prodect_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
    ]
