# Generated by Django 4.1.7 on 2023-03-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0005_alter_prodect_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodect',
            name='price',
            field=models.IntegerField(),
        ),
    ]
